services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - ./.development.env
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data: